---
- set_fact:
    _cluster_type: "{{ rosa_hosted_cp | ternary('hcp','classic') }}"

# tasks file for roles/operator-roles
- name: check for cluster
  ocm_cluster_info:
    name: "{{ cluster_name }}"
  register: _cluster_info
  no_log: true

# oidc provider
- name: get the cert chain from the host
  peer_cert_chain_info:
    host: "{{ oidc_endpoint_url }}"
  register: _oidc_endpoint_chain
  no_log: true

- set_fact:
    _oidc_endpoint_thumbprint: "{{ _oidc_endpoint_chain.ca_thumbprint | replace(':', '') }}"
    _oidc_endpoint: "{{ oidc_endpoint_url.replace('https://', '') }}"

- when: _cluster_type == 'classic'
  block:
    - name: create oidc provider for cluster
      oidc_provider:
        url: "{{ oidc_endpoint_url }}"
        client_ids: ["openshift", "sts.amazonaws.com"]
        thumbprints: "{{ _oidc_endpoint_thumbprint }}"
        tags:
          rosa_cluster_id: "{{ cluster_id }}"
      register: _oidc_provider_info

    - with_items: "{{ operator_roles[_cluster_type] }}"
      include_tasks: roles.yml

- when: _cluster_type == 'hcp'
  block:
    - name: create oidc provider for cluster
      oidc_provider:
        url: "{{ oidc_endpoint_url }}"
        client_ids: ["openshift", "sts.amazonaws.com"]
        thumbprints: "{{ _oidc_endpoint_thumbprint }}"
        tags:
          red-hat-managed: "true"
      register: _oidc_provider_info

    - set_fact:
        _oidc_config_id: "{{ oidc_id }}"

    - set_fact:
        _oidc_config_id: "{{ _cluster_info.cluster.aws.sts.oidc_config.id }}"
      when: (oidc_id is not defined) or (oidc_id == '') or (oidc_id == None)

    - name: create operator roles for HCP clusters
      command: |
        rosa create operator-roles --hosted-cp --mode auto --yes \
          --prefix "{{ cluster_name }}" \
          --oidc-config-id "{{ _oidc_config_id }}" \
          --installer-role-arn "arn:aws:iam::{{ aws_account_id }}:role/{{ rosa_account_roles_prefix }}-Installer-Role"

# - name: create oidc endpoint for cluster
#   command: "rosa create oidc-provider -c {{ _cluster_id }} --yes --mode auto"

# - fail:
