---
# tasks file for roles/operator-roles
- name: check for cluster
  ocm_cluster_info:
    name: "{{ cluster_name }}"
  register: _cluster_info

# oidc provider
- name: get the cert chain from the host
  peer_cert_chain_info:
    host: "{{ oidc_endpoint_url }}"
  register: _oidc_endpoint_chain

- set_fact:
    _oidc_endpoint_thumbprint: "{{ _oidc_endpoint_chain.ca_thumbprint | replace(':', '') }}"

- name: create oidc provider for cluster
  oidc_provider:
    url: "{{ oidc_endpoint_url }}"
    client_ids: ["openshift", "sts.amazonaws.com"]
    thumbprints: "{{ _oidc_endpoint_thumbprint }}"
    tags:
      rosa_cluster_id: "{{ cluster_id }}"
  register: _oidc_provider_info
  # until: not _oidc_provider_info.failed
  # retries: 10
  # delay: 60


# switch these to use aws native
# - name: create operator roles for cluster
#   command: "rosa create operator-roles -c {{ _cluster_id }} --yes --mode auto"

- include_tasks: ./roles.yml

# - name: create oidc endpoint for cluster
#   command: "rosa create oidc-provider -c {{ _cluster_id }} --yes --mode auto"


