---
# defaults for roles/cluster_create

cluster_name: ansible-rosa

rosa_private: false
rosa_private_link: false
rosa_disable_workload_monitoring: false
rosa_enable_autoscaling: false
rosa_hcp: false
rosa_version: "4.12.22" # 4.13.2
# rosa_min_replicas: 3
# rosa_max_replicas: 6
# wait for rosa to finish installing
rosa_wait: true
rosa_multi_az: false
rosa_admin_password: "Rosa1234password67890"
rosa_admin_username: "admin"
rosa_vpc_endpoints_enabled: false
rosa_subnet_ids: []
rosa_machine_cidr: ~
rosa_hosted_cp: False
rosa_account_roles_version: "4.13"
rosa_account_roles_prefix: AnsibleROSA
## leave commented out to use the cluster name as the prefix
# rosa_operator_roles_prefix: ~

# defaults for roles/juphost-create

# when not set will search based on ami_name
# jumphost_ami: ami-0ba62214afa52bec7
# jumphost_ami: ami-07b1d7739c91ed3fc
jumphost_ami: ""
jumphost_ami_name: "RHEL-8.8.0_HVM-*-x86_64-*Hourly*"
jumphost_instance_type: t1.micro
# jumphost_instance_type: t2.nano
# jumphost_instance_type: m4.large

# enable this if you want a second jumphost in the
# rosa private subnet, useful for testing TGW connectivity
jumphost_private_instance: false

proxy_enabled: false

# when not set will search based on ami_name
# proxy_ami: ami-0ba62214afa52bec7
proxy_ami: ""
proxy_ami_name: "RHEL-8.8.0_HVM-*-x86_64-*Hourly*"
proxy_instance_type: m4.large

# defaults for roles/vpc_create
rosa_vpc_cidr: "10.0.0.0/16"

rosa_region: "us-east-2"

## when not set the role `network_math` will attempt to figure it out
## using subnet math
# rosa_vpc_public_subnets:
#   - cidr: "10.0.128.0/17"
#     az: "us-east-2a"
#     resource_tags: { "name":"{{ cluster_name }}-public" }
# rosa_vpc_private_subnets:
#   - cidr: "10.0.0.0/17"
#     az: "us-east-2a"
#     resource_tags: { "name":"{{ cluster_name }}-private" }

# defaults file for roles/tgw_create
rosa_tgw_enabled: false

# the full CIDR that TGW should route for
rosa_egress_vpc_enabled: false
rosa_egress_vpc_multi_az: false
rosa_tgw_cidr: "10.0.0.0/8"
rosa_egress_vpc_cidr: "10.10.0.0/24"

## will be calculated if not set
# rosa_egress_vpc_public_subnets:
#   - cidr: "10.10.0.0/28"
#     az: "us-east-2a"
#     resource_tags: { "Name":"{{ cluster_name }}-egress-public" }
# rosa_egress_vpc_private_subnets:
#   - cidr: "10.10.0.16/28"
#     az: "us-east-2a"
#     resource_tags: { "Name":"{{ cluster_name }}-egress-private" }
