---
- hosts:      "all"
  connection: "local"
  vars_files:
      - vars/main.yaml

  roles:
    - name: roles/_vars
    - name: roles/network_math
    - name: roles/tgw_create
      when: rosa_tgw_enabled | bool
    - name: roles/egress_vpc_create
      when: rosa_egress_vpc_enabled | bool
    - name: roles/vpc_create
      when: rosa_subnet_ids | default([]) | length == 0
    - name: roles/jumphost_create
      when:
        - (rosa_private or rosa_private_link) or
          (enable_jumphost | default(False) | bool)
    - name: roles/proxy_create
      when:
        - (rosa_private_link | bool) and
          (proxy_enabled | default(False) | bool)
    - name: roles/account_roles_create
      when: rosa_sts | bool
    - name: roles/cluster_create
    - name: roles/dns_resolver_create
      when: rosa_tgw_enabled | bool
    - name: roles/create_admin
    - name: roles/finish


# - hosts:      "jumphost"
#   connection: "ssh"
#   remote_user: ec2-user
#   vars:
#     cluster_api: "{{ hostvars.localhost._cluster_info.cluster.api.url }}"
#   roles:
#     - name: roles/post_install
#       when:
#         - (rosa_private or rosa_private_link) or
#           (enable_jumphost | default(False) | bool)
