---
- hosts:      "all"
  connection: "local"
  vars_files:
      - vars/main.yaml

  roles:
    - name: roles/_vars
    - name: roles/cluster_delete
    - name: roles/account_roles_delete
      when: rosa_sts | bool
    - name: roles/jumphost_delete
      when:
        - (rosa_private or rosa_private_link) or
          (enable_jumphost | default(False) | bool)
    - name: roles/proxy_delete
      when:
        - (rosa_private_link | bool) and
          (proxy_enabled | default(False) | bool)
    - name: roles/tgw_delete
      when: rosa_tgw_enabled | bool
    - name: roles/egress_vpc_delete
      when: rosa_egress_vpc_enabled | bool
    - name: roles/vpc_delete
      when: rosa_subnet_ids | default([]) | length == 0




