namespace: rh_mobb
name: rosa
version: 2.0.0
readme: README.md
authors:
  - Paul Czarkowski <pczarkow@redhat.com>
  - Connor Wooley <cwooley@redhat.com>
  - Dustin Scott <dscott@redhat.com>
description: Collection of various Ansible roles and modules to manage ROSA (Red Hat OpenShift on AWS) infrastructure.
license_file: LICENSE
tags:
  - rosa
  - mobb
  - openshift
  - aws
  - redhat
dependencies: {}
repository: https://github.com/rh-mobb/ansible-rosa
documentation: https://github.com/rh-mobb/ansible-rosa
homepage: https://github.com/rh-mobb/ansible-rosa
issues: https://github.com/rh-mobb/ansible-rosa/issues
build_ignore:
  - virtualenv
  - '*.tar.gz'
  - .git
  - Dockerfile*
  - bin
  - tmp
  - temp
