---
- set_fact:
    _cluster_type: "{{ rosa_hosted_cp | ternary('hcp','classic') }}"

- with_items: "{{ operator_roles[_cluster_type] }}"
  include_tasks: roles.yml
  when: _cluster_type == 'classic'

- name: create operator roles for HCP clusters
  command: |
    rosa delete operator-roles --yes \
      --prefix "{{ cluster_name }}" --mode auto
  when: _cluster_type == 'hcp'

# - name: delete the operator roles
#   shell: |
#     rosa delete operator-roles -c {{ cluster_id }} --mode auto --yes || \
#       rosa delete operator-roles --prefix {{ operator_roles_prefix }} --mode auto --yes
#   when: (cluster_id is defined) or
#         (operator_roles_prefix is defined)

- name: delete oidc provider for cluster
  oidc_provider:
    url: "{{ oidc_endpoint_url }}"
    state: absent
  when:
    - oidc_endpoint_url is defined

# - fail:
