---
# tasks file for roles/account-roles

# - set_fact:
#     _ocp_version: "{{ rosa_version | regex_search('^[0-9]+\\.[0-9]+') }}"

- name: create support role
  iam_role:
    name: "{{ rosa_account_roles_prefix }}-Support-Role"
    assume_role_policy_document: "{{ lookup('file',(rosa_account_roles_version,'sts_support_trust_policy.json')|path_join) }}"
    tags:
      red-hat-managed: true
      rosa_role_type: support
      rosa_openshift_version: "{{ rosa_account_roles_version }}"
      rosa_role_prefix: "{{ rosa_account_roles_prefix }}"

- name: create support policy
  iam_policy:
    iam_type: role
    iam_name: "{{ rosa_account_roles_prefix }}-Support-Role"
    policy_name: "{{ rosa_account_roles_prefix }}-Support-Role-Policy"
    policy_json: "{{ lookup('file',(rosa_account_roles_version,'sts_support_permission_policy.json')|path_join) }}"

- name: create installer role
  iam_role:
    name: "{{ rosa_account_roles_prefix }}-Installer-Role"
    assume_role_policy_document: "{{ lookup('file',(rosa_account_roles_version,'sts_installer_trust_policy.json')|path_join) }}"
    tags:
      red-hat-managed: true
      rosa_role_type: installer
      rosa_openshift_version: "{{ rosa_account_roles_version }}"
      rosa_role_prefix: "{{ rosa_account_roles_prefix }}"

- name: create installer policy
  iam_policy:
    iam_type: role
    iam_name: "{{ rosa_account_roles_prefix }}-Installer-Role"
    policy_name: "{{ rosa_account_roles_prefix }}-Installer-Role-Policy"
    policy_json: "{{ lookup('file',(rosa_account_roles_version,'sts_installer_permission_policy.json')|path_join) }}"

- name: create controlplane role
  iam_role:
    name: "{{ rosa_account_roles_prefix }}-ControlPlane-Role"
    assume_role_policy_document: "{{ lookup('file',(rosa_account_roles_version,'sts_instance_controlplane_trust_policy.json')|path_join) }}"
    tags:
      red-hat-managed: true
      rosa_role_type: instance_controlplane
      rosa_openshift_version: "{{ rosa_account_roles_version }}"
      rosa_role_prefix: "{{ rosa_account_roles_prefix }}"

- name: create controlplane policy
  iam_policy:
    iam_type: role
    iam_name: "{{ rosa_account_roles_prefix }}-ControlPlane-Role"
    policy_name: "{{ rosa_account_roles_prefix }}-ControlPlane-Role-Policy"
    policy_json: "{{ lookup('file',(rosa_account_roles_version,'sts_instance_controlplane_permission_policy.json')|path_join) }}"

- name: create worker role
  iam_role:
    name: "{{ rosa_account_roles_prefix }}-Worker-Role"
    assume_role_policy_document: "{{ lookup('file',(rosa_account_roles_version,'sts_instance_worker_trust_policy.json')|path_join) }}"
    tags:
      red-hat-managed: true
      rosa_role_type: instance_worker
      rosa_openshift_version: "{{ rosa_account_roles_version }}"
      rosa_role_prefix: "{{ rosa_account_roles_prefix }}"

- name: create worker policy
  iam_policy:
    iam_type: role
    iam_name: "{{ rosa_account_roles_prefix }}-Worker-Role"
    policy_name: "{{ rosa_account_roles_prefix }}-Worker-Role-Policy"
    policy_json: "{{ lookup('file',(rosa_account_roles_version,'sts_instance_worker_permission_policy.json')|path_join) }}"

# - fail:
