---
- ec2_vpc_net_info:
    region: "{{ rosa_region }}"
    filters:
      "tag:Name": "rosa-{{ cluster_name }}-egress"
  register: vpc_info
  no_log: True

- when: vpc_info.vpcs | length > 0
  block:
    - set_fact:
        vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"

    - debug:
        var: vpc_id

    ## NAT Gateway
    - ec2_vpc_nat_gateway_info:
        region: "{{ rosa_region }}"
        filters:
          vpc-id: "{{ vpc_id }}"
      register: _nat_gw_info
      no_log: True

    - name: delete nat gateways
      ec2_vpc_nat_gateway:
        state: absent
        region: "{{ rosa_region }}"
        nat_gateway_id: "{{ item.nat_gateway_id }}"
        release_eip: yes
        wait: yes
      with_items: "{{ _nat_gw_info.result }}"
      when: item.state != 'deleted'

    # Internet Gateway
    - ec2_vpc_igw_info:
        region: "{{ rosa_region }}"
        filters:
          attachment.vpc-id: "{{ vpc_id }}"
      register: igw_info
      no_log: True

    - name: delete internet gateway
      ec2_vpc_igw:
        region: "{{ rosa_region }}"
        vpc_id: "{{ vpc_id }}"
        state: absent

    ## Subnets
    - ec2_vpc_subnet_info:
        region: "{{ rosa_region }}"
        filters:
          vpc-id: "{{ vpc_id }}"
      register: subnet_info
      no_log: True

    - name: delete private subnets
      ec2_vpc_subnet:
        region: "{{ rosa_region }}"
        state: absent
        vpc_id: "{{ vpc_id }}"
        cidr: "{{ item.cidr_block }}"
      with_items: "{{ subnet_info.subnets }}"
      when: item.state != 'deleted'

    ## Route Tables
    - ec2_vpc_route_table_info:
        filters:
          vpc-id: "{{ vpc_id }}"
        region: "{{ rosa_region }}"
      register: _route_table_info
      no_log: True

    - name: delete public subnet route table
      ec2_vpc_route_table:
        region: "{{ rosa_region }}"
        state: absent
        vpc_id: "{{ vpc_id }}"
        route_table_id: "{{ item.id }}"
        lookup: id
      with_items: "{{ _route_table_info.route_tables }}"
      when: item.associations | length == 0

    ## VPC
    - name: delete the vpc
      ec2_vpc_net:
        state: absent
        region: "{{ rosa_region }}"
        vpc_id: "{{ vpc_id }}"

