---
- include_tasks: vpc.yml

- name: add default route to tgw for egress
  transit_gateway_route:
    region: "{{ rosa_region }}"
    destination_cidr_block: 0.0.0.0/0
    transit_gateway_route_table_id: "{{ tgw_route_table }}"
    transit_gateway_attachment_id: "{{ _egress_vpc_tgw_attachment_id }}"
  register: _tgw_rt

# - fail:
